### ISSUE TITLE
Run G-PhocS with comb enabled

### ISSUE THREAD

**Issue by llq0325** [selotape/Population-Model-Compare#2]
Hi Selotape,

Could you please add an example to demonstrate how to "run Gphocs with comb enabled" ?

Regards

L

**Comment by selotape** [comment]
Hi IIq,
I'm really glad to hear you're looking into mcref!


Some answers - 
1. The GPhoCS version with reference model support isn't yet "released" but it's pretty stable as we've been working with it for a while now. I'll talk with Ilan Gronau, who's behind gphocs, about formally releasing it for you.
2. The relevant branch in gphocs repository is `mcref_dev`, If you want to play around with it.
3. To emit comb statistics in said GPhoCS version, you add the following configurations to the gphocs control file:
```
GENERAL-INFO-START
...
    comb-stats-file     out/comb-trace.tsv
    hyp-stats-file      out/hyp-trace.tsv
...
```

If you need a more full example of a control file, feel free to contact me.

Good luck and be in touch soon,
Ron

**Comment by selotape** [comment]
Added minimal example of GPhoCS usage to README

**Comment by selotape** [comment]
Added minimal example of GPhoCS usage to README
